/**
 * Country relations for related-countries algorithm.
 * Generated by scripts/generate-country-relations.mjs
 * - Regions from iso-countries.json
 * - Borders from mledoze/countries (alpha-2 codes)
 */

export interface CountryRegion {
  region: string;
  subRegion: string;
}

export const countryRegions: Record<string, CountryRegion> = {
  "AF": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "AX": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "AL": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "DZ": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "AS": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "AD": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "AO": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "AI": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "AG": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "AR": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "AM": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "AW": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "AU": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "AT": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "AZ": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "BS": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BH": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "BD": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "BB": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BY": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "BE": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "BZ": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BJ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "BM": {
    "region": "Americas",
    "subRegion": "Northern America"
  },
  "BT": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "BO": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BQ": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BA": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "BW": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "BV": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "BR": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "IO": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "BN": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "BG": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "BF": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "BI": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CV": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "KH": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "CM": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CA": {
    "region": "Americas",
    "subRegion": "Northern America"
  },
  "KY": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "CF": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "TD": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CL": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "CN": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "CX": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "CC": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "CO": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "KM": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CG": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CD": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "CK": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "CR": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "CI": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "HR": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "CU": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "CW": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "CY": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "CZ": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "DK": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "DJ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "DM": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "DO": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "EC": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "EG": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "SV": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "GQ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "ER": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "EE": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "SZ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "ET": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "FK": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "FO": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "FJ": {
    "region": "Oceania",
    "subRegion": "Melanesia"
  },
  "FI": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "FR": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "GF": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "PF": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "TF": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GA": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GM": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GE": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "DE": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "GH": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GI": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "GR": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "GL": {
    "region": "Americas",
    "subRegion": "Northern America"
  },
  "GD": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "GP": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "GU": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "GT": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "GG": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "GN": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GW": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GY": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "HT": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "HM": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "VA": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "HN": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "HK": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "HU": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "IS": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "IN": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "ID": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "IR": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "IQ": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "IE": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "IM": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "IL": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "IT": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "JM": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "JP": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "JE": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "JO": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "KZ": {
    "region": "Asia",
    "subRegion": "Central Asia"
  },
  "KE": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "KI": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "KP": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "KR": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "KW": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "KG": {
    "region": "Asia",
    "subRegion": "Central Asia"
  },
  "LA": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "LV": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "LB": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "LS": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "LR": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "LY": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "LI": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "LT": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "LU": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "MO": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "MG": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MW": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MY": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "MV": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "ML": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MT": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "MH": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "MQ": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "MR": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MU": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "YT": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MX": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "FM": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "MD": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "MC": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "MN": {
    "region": "Asia",
    "subRegion": "Eastern Asia"
  },
  "ME": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "MS": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "MA": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "MZ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "MM": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "NA": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "NR": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "NP": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "NL": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "NC": {
    "region": "Oceania",
    "subRegion": "Melanesia"
  },
  "NZ": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "NI": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "NE": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "NG": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "NU": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "NF": {
    "region": "Oceania",
    "subRegion": "Australia and New Zealand"
  },
  "MK": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "MP": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "NO": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "OM": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "PK": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "PW": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "PS": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "PA": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "PG": {
    "region": "Oceania",
    "subRegion": "Melanesia"
  },
  "PY": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "PE": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "PH": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "PN": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "PL": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "PT": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "PR": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "QA": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "RE": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "RO": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "RU": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "RW": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "BL": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "SH": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "KN": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "LC": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "MF": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "PM": {
    "region": "Americas",
    "subRegion": "Northern America"
  },
  "VC": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "WS": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "SM": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "ST": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "SA": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "SN": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "RS": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "SC": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "SL": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "SG": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "SX": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "SK": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "SI": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "SB": {
    "region": "Oceania",
    "subRegion": "Melanesia"
  },
  "SO": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "ZA": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "GS": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "SS": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "ES": {
    "region": "Europe",
    "subRegion": "Southern Europe"
  },
  "LK": {
    "region": "Asia",
    "subRegion": "Southern Asia"
  },
  "SD": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "SR": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "SJ": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "SE": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "CH": {
    "region": "Europe",
    "subRegion": "Western Europe"
  },
  "SY": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "TJ": {
    "region": "Asia",
    "subRegion": "Central Asia"
  },
  "TZ": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "TH": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "TL": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "TG": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "TK": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "TO": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "TT": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "TN": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "TR": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "TM": {
    "region": "Asia",
    "subRegion": "Central Asia"
  },
  "TC": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "TV": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "UG": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "UA": {
    "region": "Europe",
    "subRegion": "Eastern Europe"
  },
  "AE": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "GB": {
    "region": "Europe",
    "subRegion": "Northern Europe"
  },
  "US": {
    "region": "Americas",
    "subRegion": "Northern America"
  },
  "UM": {
    "region": "Oceania",
    "subRegion": "Micronesia"
  },
  "UY": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "UZ": {
    "region": "Asia",
    "subRegion": "Central Asia"
  },
  "VU": {
    "region": "Oceania",
    "subRegion": "Melanesia"
  },
  "VE": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "VN": {
    "region": "Asia",
    "subRegion": "South-eastern Asia"
  },
  "VG": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "VI": {
    "region": "Americas",
    "subRegion": "Latin America and the Caribbean"
  },
  "WF": {
    "region": "Oceania",
    "subRegion": "Polynesia"
  },
  "EH": {
    "region": "Africa",
    "subRegion": "Northern Africa"
  },
  "YE": {
    "region": "Asia",
    "subRegion": "Western Asia"
  },
  "ZM": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  },
  "ZW": {
    "region": "Africa",
    "subRegion": "Sub-Saharan Africa"
  }
};

export const countryBorders: Record<string, string[]> = {
  "AF": [
    "IR",
    "PK",
    "TM",
    "UZ",
    "TJ",
    "CN"
  ],
  "AO": [
    "CG",
    "CD",
    "ZM",
    "NA"
  ],
  "AL": [
    "ME",
    "GR",
    "MK"
  ],
  "AD": [
    "FR",
    "ES"
  ],
  "AE": [
    "OM",
    "SA"
  ],
  "AR": [
    "BO",
    "BR",
    "CL",
    "PY",
    "UY"
  ],
  "AM": [
    "AZ",
    "GE",
    "IR",
    "TR"
  ],
  "AT": [
    "CZ",
    "DE",
    "HU",
    "IT",
    "LI",
    "SK",
    "SI",
    "CH"
  ],
  "AZ": [
    "AM",
    "GE",
    "IR",
    "RU",
    "TR"
  ],
  "BI": [
    "CD",
    "RW",
    "TZ"
  ],
  "BE": [
    "FR",
    "DE",
    "LU",
    "NL"
  ],
  "BJ": [
    "BF",
    "NE",
    "NG",
    "TG"
  ],
  "BF": [
    "BJ",
    "CI",
    "GH",
    "ML",
    "NE",
    "TG"
  ],
  "BD": [
    "MM",
    "IN"
  ],
  "BG": [
    "GR",
    "MK",
    "RO",
    "RS",
    "TR"
  ],
  "BA": [
    "HR",
    "ME",
    "RS"
  ],
  "BY": [
    "LV",
    "LT",
    "PL",
    "RU",
    "UA"
  ],
  "BZ": [
    "GT",
    "MX"
  ],
  "BO": [
    "AR",
    "BR",
    "CL",
    "PY",
    "PE"
  ],
  "BR": [
    "AR",
    "BO",
    "CO",
    "GF",
    "GY",
    "PY",
    "PE",
    "SR",
    "UY",
    "VE"
  ],
  "BN": [
    "MY"
  ],
  "BT": [
    "CN",
    "IN"
  ],
  "BW": [
    "NA",
    "ZA",
    "ZM",
    "ZW"
  ],
  "CF": [
    "CM",
    "TD",
    "CD",
    "CG",
    "SS",
    "SD"
  ],
  "CA": [
    "US"
  ],
  "CH": [
    "AT",
    "FR",
    "IT",
    "LI",
    "DE"
  ],
  "CL": [
    "AR",
    "BO",
    "PE"
  ],
  "CN": [
    "AF",
    "BT",
    "MM",
    "HK",
    "IN",
    "KZ",
    "NP",
    "KP",
    "KG",
    "LA",
    "MO",
    "MN",
    "PK",
    "RU",
    "TJ",
    "VN"
  ],
  "CI": [
    "BF",
    "GH",
    "GN",
    "LR",
    "ML"
  ],
  "CM": [
    "CF",
    "TD",
    "CG",
    "GQ",
    "GA",
    "NG"
  ],
  "CD": [
    "AO",
    "BI",
    "CF",
    "CG",
    "RW",
    "SS",
    "TZ",
    "UG",
    "ZM"
  ],
  "CG": [
    "AO",
    "CM",
    "CF",
    "CD",
    "GA"
  ],
  "CO": [
    "BR",
    "EC",
    "PA",
    "PE",
    "VE"
  ],
  "CR": [
    "NI",
    "PA"
  ],
  "CZ": [
    "AT",
    "DE",
    "PL",
    "SK"
  ],
  "DE": [
    "AT",
    "BE",
    "CZ",
    "DK",
    "FR",
    "LU",
    "NL",
    "PL",
    "CH"
  ],
  "DJ": [
    "ER",
    "ET",
    "SO"
  ],
  "DK": [
    "DE"
  ],
  "DO": [
    "HT"
  ],
  "DZ": [
    "TN",
    "LY",
    "NE",
    "EH",
    "MR",
    "ML",
    "MA"
  ],
  "EC": [
    "CO",
    "PE"
  ],
  "EG": [
    "IL",
    "LY",
    "PS",
    "SD"
  ],
  "ER": [
    "DJ",
    "ET",
    "SD"
  ],
  "EH": [
    "DZ",
    "MR",
    "MA"
  ],
  "ES": [
    "AD",
    "FR",
    "GI",
    "PT",
    "MA"
  ],
  "EE": [
    "LV",
    "RU"
  ],
  "ET": [
    "DJ",
    "ER",
    "KE",
    "SO",
    "SS",
    "SD"
  ],
  "FI": [
    "NO",
    "SE",
    "RU"
  ],
  "FR": [
    "AD",
    "BE",
    "DE",
    "IT",
    "LU",
    "MC",
    "ES",
    "CH"
  ],
  "GA": [
    "CM",
    "CG",
    "GQ"
  ],
  "GB": [
    "IE"
  ],
  "GE": [
    "AM",
    "AZ",
    "RU",
    "TR"
  ],
  "GH": [
    "BF",
    "CI",
    "TG"
  ],
  "GI": [
    "ES"
  ],
  "GN": [
    "CI",
    "GW",
    "LR",
    "ML",
    "SN",
    "SL"
  ],
  "GM": [
    "SN"
  ],
  "GW": [
    "GN",
    "SN"
  ],
  "GQ": [
    "CM",
    "GA"
  ],
  "GR": [
    "AL",
    "BG",
    "TR",
    "MK"
  ],
  "GT": [
    "BZ",
    "SV",
    "HN",
    "MX"
  ],
  "GF": [
    "BR",
    "SR"
  ],
  "GY": [
    "BR",
    "SR",
    "VE"
  ],
  "HK": [
    "CN"
  ],
  "HN": [
    "GT",
    "SV",
    "NI"
  ],
  "HR": [
    "BA",
    "HU",
    "ME",
    "RS",
    "SI"
  ],
  "HT": [
    "DO"
  ],
  "HU": [
    "AT",
    "HR",
    "RO",
    "RS",
    "SK",
    "SI",
    "UA"
  ],
  "ID": [
    "TL",
    "MY",
    "PG"
  ],
  "IN": [
    "BD",
    "BT",
    "MM",
    "CN",
    "NP",
    "PK"
  ],
  "IE": [
    "GB"
  ],
  "IR": [
    "AF",
    "AM",
    "AZ",
    "IQ",
    "PK",
    "TR",
    "TM"
  ],
  "IQ": [
    "IR",
    "JO",
    "KW",
    "SA",
    "SY",
    "TR"
  ],
  "IL": [
    "EG",
    "JO",
    "LB",
    "PS",
    "SY"
  ],
  "IT": [
    "AT",
    "FR",
    "SM",
    "SI",
    "CH",
    "VA"
  ],
  "JO": [
    "IQ",
    "IL",
    "PS",
    "SA",
    "SY"
  ],
  "KZ": [
    "CN",
    "KG",
    "RU",
    "TM",
    "UZ"
  ],
  "KE": [
    "ET",
    "SO",
    "SS",
    "TZ",
    "UG"
  ],
  "KG": [
    "CN",
    "KZ",
    "TJ",
    "UZ"
  ],
  "KH": [
    "LA",
    "TH",
    "VN"
  ],
  "KR": [
    "KP"
  ],
  "XK": [
    "AL",
    "MK",
    "ME",
    "RS"
  ],
  "KW": [
    "IQ",
    "SA"
  ],
  "LA": [
    "MM",
    "KH",
    "CN",
    "TH",
    "VN"
  ],
  "LB": [
    "IL",
    "SY"
  ],
  "LR": [
    "GN",
    "CI",
    "SL"
  ],
  "LY": [
    "DZ",
    "TD",
    "EG",
    "NE",
    "SD",
    "TN"
  ],
  "LI": [
    "AT",
    "CH"
  ],
  "LK": [
    "IN"
  ],
  "LS": [
    "ZA"
  ],
  "LT": [
    "BY",
    "LV",
    "PL",
    "RU"
  ],
  "LU": [
    "BE",
    "FR",
    "DE"
  ],
  "LV": [
    "BY",
    "EE",
    "LT",
    "RU"
  ],
  "MO": [
    "CN"
  ],
  "MF": [
    "SX"
  ],
  "MA": [
    "DZ",
    "EH",
    "ES"
  ],
  "MC": [
    "FR"
  ],
  "MD": [
    "RO",
    "UA"
  ],
  "MX": [
    "BZ",
    "GT",
    "US"
  ],
  "MK": [
    "AL",
    "BG",
    "GR",
    "RS"
  ],
  "ML": [
    "DZ",
    "BF",
    "GN",
    "CI",
    "MR",
    "NE",
    "SN"
  ],
  "MM": [
    "BD",
    "CN",
    "IN",
    "LA",
    "TH"
  ],
  "ME": [
    "AL",
    "BA",
    "HR",
    "RS"
  ],
  "MN": [
    "CN",
    "RU"
  ],
  "MZ": [
    "MW",
    "ZA",
    "SZ",
    "TZ",
    "ZM",
    "ZW"
  ],
  "MR": [
    "DZ",
    "ML",
    "SN",
    "EH"
  ],
  "MW": [
    "MZ",
    "TZ",
    "ZM"
  ],
  "MY": [
    "BN",
    "ID",
    "TH"
  ],
  "NA": [
    "AO",
    "BW",
    "ZA",
    "ZM"
  ],
  "NE": [
    "DZ",
    "BJ",
    "BF",
    "TD",
    "LY",
    "ML",
    "NG"
  ],
  "NG": [
    "BJ",
    "CM",
    "TD",
    "NE"
  ],
  "NI": [
    "CR",
    "HN"
  ],
  "NL": [
    "BE",
    "DE"
  ],
  "NO": [
    "FI",
    "SE",
    "RU"
  ],
  "NP": [
    "CN",
    "IN"
  ],
  "OM": [
    "SA",
    "AE",
    "YE"
  ],
  "PK": [
    "AF",
    "CN",
    "IN",
    "IR"
  ],
  "PA": [
    "CO",
    "CR"
  ],
  "PE": [
    "BO",
    "BR",
    "CL",
    "CO",
    "EC"
  ],
  "PG": [
    "ID"
  ],
  "PL": [
    "BY",
    "CZ",
    "DE",
    "LT",
    "RU",
    "SK",
    "UA"
  ],
  "KP": [
    "CN",
    "KR",
    "RU"
  ],
  "PT": [
    "ES"
  ],
  "PY": [
    "AR",
    "BO",
    "BR"
  ],
  "PS": [
    "IL",
    "EG",
    "JO"
  ],
  "QA": [
    "SA"
  ],
  "RO": [
    "BG",
    "HU",
    "MD",
    "RS",
    "UA"
  ],
  "RU": [
    "AZ",
    "BY",
    "CN",
    "EE",
    "FI",
    "GE",
    "KZ",
    "KP",
    "LV",
    "LT",
    "MN",
    "NO",
    "PL",
    "UA"
  ],
  "RW": [
    "BI",
    "CD",
    "TZ",
    "UG"
  ],
  "SA": [
    "IQ",
    "JO",
    "KW",
    "OM",
    "QA",
    "AE",
    "YE"
  ],
  "SD": [
    "CF",
    "TD",
    "EG",
    "ER",
    "ET",
    "LY",
    "SS"
  ],
  "SN": [
    "GM",
    "GN",
    "GW",
    "ML",
    "MR"
  ],
  "SL": [
    "GN",
    "LR"
  ],
  "SV": [
    "GT",
    "HN"
  ],
  "SM": [
    "IT"
  ],
  "SO": [
    "DJ",
    "ET",
    "KE"
  ],
  "RS": [
    "BA",
    "BG",
    "HR",
    "HU",
    "MK",
    "ME",
    "RO"
  ],
  "SS": [
    "CF",
    "CD",
    "ET",
    "KE",
    "SD",
    "UG"
  ],
  "SR": [
    "BR",
    "GF",
    "GY"
  ],
  "SK": [
    "AT",
    "CZ",
    "HU",
    "PL",
    "UA"
  ],
  "SI": [
    "AT",
    "HR",
    "IT",
    "HU"
  ],
  "SE": [
    "FI",
    "NO"
  ],
  "SZ": [
    "MZ",
    "ZA"
  ],
  "SX": [
    "MF"
  ],
  "SY": [
    "IQ",
    "IL",
    "JO",
    "LB",
    "TR"
  ],
  "TD": [
    "CM",
    "CF",
    "LY",
    "NE",
    "NG",
    "SD"
  ],
  "TG": [
    "BJ",
    "BF",
    "GH"
  ],
  "TH": [
    "MM",
    "KH",
    "LA",
    "MY"
  ],
  "TJ": [
    "AF",
    "CN",
    "KG",
    "UZ"
  ],
  "TM": [
    "AF",
    "IR",
    "KZ",
    "UZ"
  ],
  "TL": [
    "ID"
  ],
  "TN": [
    "DZ",
    "LY"
  ],
  "TR": [
    "AM",
    "AZ",
    "BG",
    "GE",
    "GR",
    "IR",
    "IQ",
    "SY"
  ],
  "TZ": [
    "BI",
    "CD",
    "KE",
    "MW",
    "MZ",
    "RW",
    "UG",
    "ZM"
  ],
  "UG": [
    "CD",
    "KE",
    "RW",
    "SS",
    "TZ"
  ],
  "UA": [
    "BY",
    "HU",
    "MD",
    "PL",
    "RO",
    "RU",
    "SK"
  ],
  "UY": [
    "AR",
    "BR"
  ],
  "US": [
    "CA",
    "MX"
  ],
  "UZ": [
    "AF",
    "KZ",
    "KG",
    "TJ",
    "TM"
  ],
  "VA": [
    "IT"
  ],
  "VE": [
    "BR",
    "CO",
    "GY"
  ],
  "VN": [
    "KH",
    "CN",
    "LA"
  ],
  "YE": [
    "OM",
    "SA"
  ],
  "ZA": [
    "BW",
    "LS",
    "MZ",
    "NA",
    "SZ",
    "ZW"
  ],
  "ZM": [
    "AO",
    "BW",
    "CD",
    "MW",
    "MZ",
    "NA",
    "TZ",
    "ZW"
  ],
  "ZW": [
    "BW",
    "MZ",
    "ZA",
    "ZM"
  ]
};

/** Minimal shape for getRelatedCountries - matches LegalNameChangeGuide */
interface GuideForRelated {
  country: string;
  countryCode: string;
  flag: string;
  difficulty: string;
  estimatedCostUSD: [number, number];
}

/**
 * Get related countries for a guide using a similarity algorithm:
 * - Bordering countries (highest weight)
 * - Same region
 * - Same sub-region
 * - Same difficulty
 * - Similar cost range
 */
export function getRelatedCountries(
  guide: GuideForRelated,
  allGuides: GuideForRelated[],
  limit = 6
): GuideForRelated[] {
  const code = normalizeCode(guide.countryCode);
  const myRegion = countryRegions[code];
  const myBorders = new Set(countryBorders[code] || []);

  const scored = allGuides
    .filter((g) => normalizeCode(g.countryCode) !== code)
    .map((g) => {
      const c = normalizeCode(g.countryCode);
      let score = 0;

      if (myBorders.has(c)) score += 50;
      if (myRegion?.region && countryRegions[c]?.region === myRegion.region) score += 20;
      if (myRegion?.subRegion && countryRegions[c]?.subRegion === myRegion.subRegion) score += 30;
      if (g.difficulty === guide.difficulty) score += 10;

      const a = guide.estimatedCostUSD;
      const b = g.estimatedCostUSD;
      if (Array.isArray(a) && Array.isArray(b) && a.length >= 2 && b.length >= 2) {
        const [a1, a2] = a;
        const [b1, b2] = b;
        const overlap = Math.max(0, Math.min(a2, b2) - Math.max(a1, b1));
        if (overlap > 0 || (a1 <= b2 && b1 <= a2)) score += 5;
      }

      return { guide: g, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map((x) => x.guide);
}

function normalizeCode(code: string): string {
  return code.split("-")[0];
}
